import {
	sleekai,
	neurai,
	cineseek,
	maganime,
	utube,
	moviebox,
	deliverfy,
	rolexie,
	travelgeek,
	eleccar,
	yummey,
	elibft,
	clicknshop,
} from "../assets/images";

export const projects = [
	{
		title: "Neurai",
		imgSrc: neurai,
		liveLink: "https://neurai.vercel.app/",
		githubLink: "https://github.com/jaytintran/neurai",
		type: "highlighted",
	},
	{
		title: "Neurai",
		imgSrc: neurai,
		liveLink: "https://neurai.vercel.app/",
		githubLink: "https://github.com/jaytintran/neurai",
		type: "mern",
	},
	{
		title: "Sleekai",
		imgSrc: sleekai,
		liveLink: "https://sleek-ai-orpin.vercel.app/",
		githubLink: "https://github.com/jaytintran/sleek-ai",
		type: "highlighted",
	},
	{
		title: "CineSeek",
		imgSrc: cineseek,
		liveLink: "https://cine-seek-six.vercel.app/",
		githubLink: "https://github.com/jaytintran/cineseek",
		type: "highlighted",
	},
	{
		title: "Maganime",
		imgSrc: maganime,
		liveLink: "https://jaytintran.github.io/maganime",
		githubLink: "https://github.com/jaytintran/maganime",
		type: "front-end",
	},
	{
		title: "U-Tube",
		imgSrc: utube,
		liveLink: "https://jaytintran.github.io/utube-react-app",
		githubLink: "https://utube-v1.netlify.app/",
		type: "front-end",
	},
	{
		title: "Movie Box",
		imgSrc: moviebox,
		liveLink: "https://jaytintran.github.io/movie-box",
		githubLink: "https://github.com/jaytintran/movie-box",
		type: "front-end",
	},
	{
		title: "Deliverfy",
		imgSrc: deliverfy,
		liveLink: "https://jaytintran.github.io/deliverfy",
		githubLink: "https://github.com/jaytintran/deliverfy",
		type: "ux/ui",
	},
	{
		title: "Rolexie",
		imgSrc: rolexie,
		liveLink: "https://jaytintran.github.io/rolexie",
		githubLink: "https://github.com/jaytintran/rolexie",
		type: "ux/ui",
	},
	{
		title: "Travel Geek",
		imgSrc: travelgeek,
		liveLink: "https://jaytintran.github.io/travel-geek",
		githubLink: "https://github.com/jaytintran/travel-geek",
		type: "ux/ui",
	},
	{
		title: "Elec-car",
		imgSrc: eleccar,
		liveLink: "https://jaytintran.github.io/elec-car",
		githubLink: "https://github.com/jaytintran/elec-car",
		type: "ux/ui",
	},
	{
		title: "Yummey",
		imgSrc: yummey,
		liveLink: "https://jaytintran.github.io/yummey",
		githubLink: "https://github.com/jaytintran/yummey",
		type: "ux/ui",
	},
	{
		title: "Online Library",
		imgSrc: elibft,
		liveLink: "https://jaytintran.github.io/e-libft",
		githubLink: "https://github.com/jaytintran/e-libft",
		type: "front-end",
	},
	{
		title: "ClicknShop",
		imgSrc: clicknshop,
		liveLink: "https://click-n-shop-mern-stack.onrender.com/",
		githubLink: "https://github.com/jaytintran/full-stack-simple-product-store",
		type: "mern",
	},
	{
		title: "ClicknShop",
		imgSrc: clicknshop,
		liveLink: "https://click-n-shop-mern-stack.onrender.com/",
		githubLink: "https://github.com/jaytintran/full-stack-simple-product-store",
		type: "highlighted",
	},
];
